services:
  db:
    image: postgres:16
    restart: unless-stopped #si el ocntenedor se cae Docker lo vuelve a arrancar solo
    environment:
      POSTGRES_USER: ${DB_USER} #${DB_USER} es una variable de entorno que se define en el archivo .env, igual ocn otodos los ${}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 1m30s
      #Cuanto espera el comando test por la respuesta antes de darla por fallida
      timeout: 10s
      retries: 3
      #start_period sirven para dar un pequeño margen al arrancar los servicios y omiten los fallos durante este periodo de tiempo, por ejemplo para evitar fallos mientras arranca postgres 
      start_period: 40s
      #start_interval es el tiempo que espera entre cada intento de testeo del servicio hasta que se detecta que esta corriendo por primera vez
      start_interval: 5s

  api:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db:
          condition: service_healthy
          #
          restart: true


volumes:
  pgdata: